definitions:
  model.ActorDto:
    properties:
      date_Of_birth:
        type: string
      gender:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /actor:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ActorDto'
      summary: Создание актера
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
